version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  percy-dev: pixolith/percy-dev@1.0.8
workflows:
  commit-workflow:
      jobs:
        - cypress/run:
            browser: electron
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
        - cypress/run:
            browser: electron
  percy-workflow:
    jobs:
      - percy-dev/run_test
